package net.nolifers.storyoflife.init.event;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.nolifers.storyoflife.init.StoryofLife;

/**
 * This is a special class that listens to registry events, to allow creation of mod blocks and items at the proper time.
 * Code auto generated by Minecraft Dev plugin for IntelliJ IDEA :
 */
@Mod.EventBusSubscriber(modid=StoryofLife.MOD_ID)
public class RegistryEventHandler {
    /**
     * Listen for the register event for creating custom items
     */
    @SubscribeEvent
    public static void addItems(RegistryEvent.Register<Item> event) {

    }

    /**
     * Listen for the register event for creating custom blocks
     */
    @SubscribeEvent
    public static void addBlocks(RegistryEvent.Register<Block> event) {

    }
}