package net.nolifers.storyoflife.event;

import net.minecraft.block.Block;
import net.minecraft.entity.EnumCreatureType;
import net.minecraft.init.Biomes;
import net.minecraft.world.biome.Biome;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.registry.EntityEntryBuilder;
import net.nolifers.storyoflife.StoryofLife;
import net.nolifers.storyoflife.entity.EntityWildebeast;

/**
 * This is a special class that listens to registry events, to allow creation of mod blocks and items at the proper time.
 * Code auto generated by Minecraft Dev plugin for IntelliJ IDEA :
 */
@Mod.EventBusSubscriber(modid=StoryofLife.MOD_ID)
public class RegistryEventHandler {
    /**
     * Listen for the register event for creating custom items
     */
    @SubscribeEvent
    public static void addItems(RegistryEvent.Register<Item> event) {

    }

    /**
     * Listen for the register event for creating custom blocks
     */
    @SubscribeEvent
    public static void addBlocks(RegistryEvent.Register<Block> event) {

    }

    @SubscribeEvent
    public static void addEntities(RegistryEvent.Register<EntityEntry> event){
        int EntityID= 0;
        event.getRegistry().registerAll(
                EntityEntryBuilder.create()
                .entity(EntityWildebeast.class)
                .id(new ResourceLocation(StoryofLife.MOD_ID,"wildebeast"),EntityID++)
                .name(StoryofLife.MOD_ID+".wildebeast")
                .tracker(64,3,true)
                .egg(0,0).
                        spawn(EnumCreatureType.CREATURE,14,5,8, new Biome[]{Biomes.SAVANNA,Biomes.MUTATED_SAVANNA,Biomes.SAVANNA_PLATEAU})
                .build()
                );
    }

    static ItemBlock createBasicItemBlock(Block b){
        return (ItemBlock)(new ItemBlock(b).setRegistryName(b.getRegistryName()));
    }

}